IIA/Models/TrainingCalendarViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IIA.Models
{
    public class TrainingCalendarViewModel
    {
       
       public List<TrainingCalendarCourse> trainingCalendarCourses { get; set; }

    }
}

IIA/Controllers/DashboardController.cs
using System;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using IIA.DBContext;
using System.Linq.Dynamic;
using umbraco.cms.helpers;
using System.Linq;
using System.Collections.Generic;
using System.Web;
using IIA.Models;
using CMS.Helpers;
using System.Data.Entity;
using Umbraco.Web;
using System.Web.Configuration;
using System.Text;
using System.Net;
using System.IO;
using System.Web.Script.Serialization;
using umbraco.editorControls.SettingControls.Pickers;
using Newtonsoft.Json;
using Umbraco.Core.Models;
using IIA.Helper;
using Umbraco.Web.Media.EmbedProviders;
using System.Runtime.Remoting.Metadata.W3cXsd2001;
using umbraco.MacroEngines;
using umbraco.presentation;

namespace IIA.Controllers
{
    public class DashboardController : SurfaceController
    {
        IIAContext db = new IIAContext();
        [HttpGet]
        public ActionResult TopMenu()
        {
            try
            {
                var lang = Utility.GetLanguageFromUrl(HttpContext.Request.Url.ToString());

                RegistrationViewModel model = new RegistrationViewModel();
                long ProfileId = long.Parse(Utility.GetApplicationCookies("proId").Value);
                ctRegistration objDbModel = db.ctRegistrations.Where(x => x.ProfileId == ProfileId).FirstOrDefault();
                string middleName = lang == "en" ? objDbModel.MiddleName : objDbModel.MiddleName_ar;
                model.MembershipType = objDbModel.MembershipType;
                model.MembershipBadge = objDbModel.MembershipBadge;
                model.FirstName = lang == "en" ? objDbModel.FirstName : objDbModel.FirstName_ar;
                model.MiddleName = !string.IsNullOrEmpty(middleName) ? middleName : "";
                model.LastName = lang == "en" ? objDbModel.LastName : objDbModel.LastName_ar;
                if (!string.IsNullOrEmpty(objDbModel.ProfilePhoto))
                {
                    model.ProfilePhoto = "/Media/ApplicantFile/" + objDbModel.ProfilePhoto;
                }
                else
                {
                    model.ProfilePhoto = "/ui/media/images/avater.jpg";
                }


                model.ProfileType = objDbModel.ProfileType;
                model.ParentProfileId = objDbModel.ParentProfileId;
                return PartialView("Dashboard/TopMenu", model);
            }
            catch (Exception ex)
            {

            }

            return HttpNotFound();
        }

        [HttpGet]
        public ActionResult LeftMenu()
        {
            try
            {
                LeftMenuModel leftMenuModel = new LeftMenuModel();
                RegistrationViewModel model = new RegistrationViewModel();
                long ProfileId = long.Parse(Utility.GetApplicationCookies("proId").Value);
                ctRegistration objDbModel = db.ctRegistrations.Where(x => x.ProfileId == ProfileId).FirstOrDefault();
                model.MembershipType = objDbModel.MembershipType;
                model.ParentProfileId = objDbModel.ParentProfileId;
                model.ProfileType = objDbModel.ProfileType;
                model.MembershipEndDate = objDbModel.MembershipEndDate;
                leftMenuModel.RegistrationViewModel = model;
                if (canMemberApplyForCandidate(objDbModel))
                {
                    leftMenuModel.Elections = getOpenElectionsForApply();
                }
                return PartialView("Dashboard/LeftMenu", leftMenuModel);
            }
            catch (Exception ex)
            {

            }

            return HttpNotFound();
        }

        [HttpGet]
        public ActionResult UserProfile()
        {
            try
            {
                var lang = Utility.GetLanguageFromUrl(HttpContext.Request.Url.ToString());

                UserProfileDashboardModel model = new UserProfileDashboardModel();

                RegistrationViewModel RegisterInfo = new RegistrationViewModel();

                List<InvoiceDetailsModel> PurchaseList = new List<InvoiceDetailsModel>();

                long ProfileId = long.Parse(Utility.GetApplicationCookies("proId").Value);
                ctRegistration objDbModel = db.ctRegistrations.Where(x => x.ProfileId == ProfileId).FirstOrDefault();

                string middleName = lang == "en" ? objDbModel.MiddleName : objDbModel.MiddleName_ar;

                RegisterInfo.FirstName = lang == "en" ? objDbModel.FirstName : objDbModel.FirstName_ar;
                RegisterInfo.MiddleName = !string.IsNullOrEmpty(middleName) ? middleName : "";
                RegisterInfo.LastName = lang == "en" ? objDbModel.LastName : objDbModel.LastName_ar;

                if (!string.IsNullOrEmpty(objDbModel.ProfilePhoto))
                {
                    RegisterInfo.ProfilePhoto = "/Media/ApplicantFile/" + objDbModel.ProfilePhoto;
                }
                else
                {
                    RegisterInfo.ProfilePhoto = "/ui/media/images/avater.jpg";
                }


                RegisterInfo.JobTitle = lang == "en" ? objDbModel.JobTitle : objDbModel.JobTitle_ar;
                RegisterInfo.Organization = lang == "en" ? objDbModel.Organization : objDbModel.Organization_ar;
                RegisterInfo.EmailAddress = objDbModel.EmailAddress;
                RegisterInfo.Qualification = lang == "en" ? objDbModel.Qualification : objDbModel.Qualification_ar;
                RegisterInfo.Bio = lang == "en" ? objDbModel.Bio : objDbModel.Bio_ar;
                RegisterInfo.Experience = lang == "en" ? objDbModel.Experience : objDbModel.Experience_ar;
                RegisterInfo.MobileNumber = objDbModel.MobileNumber;
                RegisterInfo.PhoneNumber = objDbModel.PhoneNumber;
                RegisterInfo.ProfileType = objDbModel.ProfileType;
                RegisterInfo.MemberActivationDate = objDbModel.MemberActivationDate;
                RegisterInfo.Country = db.CountryLists.Where(x => x.CountryCode == objDbModel.Country).FirstOrDefault().CountryName;
                RegisterInfo.City = lang == "en" ? objDbModel.City : objDbModel.City_ar;
                RegisterInfo.ProfileId = objDbModel.ProfileId;
                RegisterInfo.ParentProfileId = objDbModel.ParentProfileId;
                RegisterInfo.MembershipType = objDbModel.MembershipType;
                RegisterInfo.IIAGlobalNumber = objDbModel.IIAGlobalNumber;
                RegisterInfo.MembershipEndDate = objDbModel.MembershipEndDate;

                try
                {
                    var Invoice = db.ctInvoices.Where(x => x.ProfileId == ProfileId).ToList();

                    foreach (var invoiceMain in Invoice)
                    {
                        var InvoiceItem = db.ctInvoiceDetails.Where(x => x.InvoiceId == invoiceMain.InvoiceId).ToList();
                        foreach (var item in InvoiceItem)
                        {
                            InvoiceDetailsModel invoiceModel = new InvoiceDetailsModel();
                            if (item.ProductType == "C")
                            {
                                invoiceModel.CourseCmsName = Umbraco.TypedContent(item.CourseCmsId).GetPropertyValue("courseTitle").ToString();
                                invoiceModel.LevelCmsName = Umbraco.TypedContent(item.LevelCmsId).GetPropertyValue("courseLevel").ToString();
                                invoiceModel.StudyMethodCmsName = Umbraco.TypedContent(item.StudyMethodCmsId).GetPropertyValue("title").ToString();
                                invoiceModel.StartDate = item.StartDate;
                                invoiceModel.EndDate = item.EndDate;
                            }
                            else
                            {
                                invoiceModel.ProductCmsName = Umbraco.TypedContent(item.ProductCmsId).GetPropertyValue("title").ToString();
                                invoiceModel.ProductPicture = Umbraco.TypedContent(item.ProductCmsId).GetPropertyValue<IPublishedContent>("image").Url.ToString();

                            }

                            invoiceModel.Price = item.Price.Value;
                            invoiceModel.Discount = item.Discount.Value;
                            invoiceModel.Quantity = item.Quantity.Value;
                            invoiceModel.ProductType = item.ProductType;

                            PurchaseList.Add(invoiceModel);
                        }
                    }

                }
                catch
                {

                }

                model.RegisterInfo = RegisterInfo;
                model.PurchaseList = PurchaseList;


                return PartialView("Dashboard/UserProfile", model);
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    status = false,
                    message = ex.Message.ToString()
                }, JsonRequestBehavior.AllowGet);


            }

        }

        [HttpGet]
        public ActionResult Financial()
        {
            try
            {
                RegistrationViewModel model = new RegistrationViewModel();
                long ProfileId = long.Parse(Utility.GetApplicationCookies("proId").Value);
                ctRegistration objDbModel = db.ctRegistrations.Where(x => x.ProfileId == ProfileId).FirstOrDefault();
                model.MembershipType = objDbModel.MembershipType;
                model.MembershipBadge = objDbModel.MembershipBadge;
                model.MembershipDiscount = objDbModel.MembershipDiscount != null ? objDbModel.MembershipDiscount.Value : 0;
                model.ProfileType = objDbModel.ProfileType;
                model.MemberActivationDate = objDbModel.MemberActivationDate != null ? objDbModel.MemberActivationDate : null;
                model.MembershipStartDate = objDbModel.MembershipStartDate != null ? objDbModel.MembershipStartDate : null;

IIA/Controllers/EventController.cs
using System;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using IIA.DBContext;
using System.Linq.Dynamic;
using umbraco.cms.helpers;
using System.Linq;
using System.Collections.Generic;
using System.Web;
using IIA.Models;
using CMS.Helpers;
using System.Data.Entity;
using Umbraco.Web;
using System.Web.Configuration;
using System.Text;
using System.Net;
using System.IO;
using System.Web.Script.Serialization;
using umbraco.editorControls.SettingControls.Pickers;
using Newtonsoft.Json;
using System.Runtime.Serialization;
using Umbraco.Core.Models;
using IIA.Helper;

namespace IIA.Controllers
{
    public class EventController : SurfaceController
    {
        IIAContext db = new IIAContext();
        [HttpPost]
        public JsonResult GetEvents(string lang, string date, string pastEvent, string eventTypeId, string page)
        {
            try
            {
                int pageIndex = !string.IsNullOrEmpty(page) ? int.Parse(page) : 1;
                int pageSize = 8;
                int totalPage = 0;

                List<EventsViewModelcs> listItem = new List<EventsViewModelcs>();

                int EventsID = lang == "en" ? 2384 : 2516;
                var Events = Umbraco.TypedContent(EventsID);

                var EventList = Events.Descendants().Where(x => x.DocumentTypeAlias == "eventsItem" && x.IsVisible() && x.GetPropertyValue<DateTime>("date") >= DateTime.Now.Date).OrderByDescending(x => x.GetPropertyValue<DateTime>("date")).ToList();

                if(!string.IsNullOrEmpty(pastEvent))
                {
                    EventList= Events.Descendants().Where(x => x.DocumentTypeAlias == "eventsItem" && x.IsVisible() && x.GetPropertyValue<DateTime>("date") <= DateTime.Now.Date).OrderByDescending(x => x.GetPropertyValue<DateTime>("date")).ToList();
                }

                if (!string.IsNullOrEmpty(eventTypeId))
                {
                    EventList = EventList.Where(x => x.Parent.Id == int.Parse(eventTypeId)).OrderByDescending(x => x.GetPropertyValue<DateTime>("date")).ToList();
                }

                if (!string.IsNullOrEmpty(date))
                {
                    date = date.Replace("to", "#");
                    var dateList = date.Split('#');

                    if (dateList.Length > 1)
                    {
                        EventList = EventList.Where(x => x.GetPropertyValue<DateTime>("date") >= DateTime.Parse(dateList[0].ToString().Trim()) && x.GetPropertyValue<DateTime>("date") <= DateTime.Parse(dateList[1].ToString().Trim())).OrderByDescending(x => x.GetPropertyValue<DateTime>("date")).ToList();
                    }
                    else
                    {
                        EventList = EventList.Where(x => x.GetPropertyValue<DateTime>("date") >= DateTime.Parse(dateList[0].ToString().Trim())).OrderByDescending(x => x.GetPropertyValue<DateTime>("date")).ToList();
                    }


                }
                foreach (var item in EventList)
                {
                    EventsViewModelcs lItem = new EventsViewModelcs();
                    lItem.EventId = item.Id;
                    lItem.EventCmsName = item.Name;
                    lItem.Title = item.GetPropertyValue("title").ToString();
                    lItem.Introduction = item.GetPropertyValue("introduction").ToString();
                    lItem.City = item.GetPropertyValue("city").ToString();
                    lItem.Type = item.GetPropertyValue("type").ToString();
                    lItem.Date = item.GetPropertyValue("displayDate").ToString();
                    lItem.Time = item.GetPropertyValue("time").ToString();
                    lItem.Image = item.GetPropertyValue<IPublishedContent>("thumbnail").Url.ToString();
                    lItem.Url = item.Url;
                    listItem.Add(lItem);
                }

                totalPage = (int)Math.Ceiling((double)listItem.Count() / pageSize);

                return Json(new { status = true, EventList = listItem, totalPage = totalPage }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { status = false, message = ex.Message.ToString() }, JsonRequestBehavior.AllowGet);
            }

        }

        [HttpPost]
        public ActionResult EventRegister(EventRegisterModel model)
        {
            try
            {
                EventRegister dbModel = new EventRegister()
                {
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    EmailAddress = model.EmailAddress,
                    ContactNo = model.ContactNo,
                    Country = db.CountryLists.Where(x => x.CountryCode == model.Country).FirstOrDefault().CountryName,
                    City = model.City,
                    ZipCode = model.ZipCode,
                    EventId=model.EventId,
                    EventCmsName=model.EventCmsName,
                    RegistrationDate=DateTime.Now                  
                };

                db.EventRegisters.Add(dbModel);
                db.SaveChanges();

                var eventContent = Umbraco.TypedContent(model.EventId);

                EmailSettingModel eModel = Utility.GetEmailSettingEvent("EventRegister", "", "", model.lang);

                string Message = EmailMessage.GetEventRegistrationMessage(dbModel, model.lang);

                Utility.SendMail(eModel.FromName, eModel.FromEmail, eModel.EmailTo, eModel.EmailCC, eModel.EmailBCC, eModel.Subject, Message);

                EmailSettingModel eModelUser = Utility.GetEmailSettingEvent("EventRegisterUser", model.EmailAddress, eventContent.GetPropertyValue("emailSubject").ToString(), model.lang);

                string MessageUser = EmailMessage.GetEventRegistrationMessageUser(dbModel.FirstName, eventContent.GetPropertyValue("emailMessage").ToString(), eventContent.GetPropertyValue("displayDate").ToString(), eventContent.GetPropertyValue("time").ToString(), eventContent.GetPropertyValue("place").ToString(), eventContent.GetPropertyValue("googleMapLink").ToString(), model.lang);

                Utility.SendMail(eModelUser.FromName, eModelUser.FromEmail, eModelUser.EmailTo, eModelUser.EmailCC, eModelUser.EmailBCC, eModelUser.Subject, MessageUser);

                return Json(new
                {
                    status = true,
                    message = ""
                }, JsonRequestBehavior.AllowGet);
            }

            catch (Exception ex)
            {
                return Json(new
                {
                    status = false,
                    message = ""
                }, JsonRequestBehavior.AllowGet);
            }


        }
    }
}

IIA/Views/AnnualGeneralMeeting.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@using CMS.Helpers;
@{

    Layout = "Master.cshtml";
    var currentPage = Model.AncestorOrSelf();
    int pageId = UmbracoContext.Current.PageId.Value;
    var lang = Utility.GetLanguage(pageId);
    var image = Model.GetPropertyValue<IPublishedContent>("image");
    var Parent = currentPage.Parent;
}
<!-- Start Main Content -->
<main class="main">
    <!-- Start Links ban-->
    <div class="links-nav">
        <div class="container-fluid">
            <span>@Umbraco.GetDictionaryValue("You are here") :</span>
            <a href="/@lang/">@Umbraco.GetDictionaryValue("Home") <i class="fal fa-caret-right"></i></a>
            <a href="@Parent.Parent.Parent.Parent.Url">@Parent.Parent.Parent.Parent.GetPropertyValue("title")<i class="fal fa-caret-right"></i></a>
            <a href="@Parent.Parent.Parent.Url">@Parent.Parent.Parent.GetPropertyValue("title") <i class="fal fa-caret-right"></i></a>
            <a href="@Parent.Parent.Url">@Parent.Parent.GetPropertyValue("title") <i class="fal fa-caret-right"></i></a>
            <a href="@Parent.Parent.Url">@Parent.GetPropertyValue("title") <i class="fal fa-caret-right"></i></a>
            <a href="#" class="active">@Model.GetPropertyValue("title") <i class="fal fa-caret-right"></i></a>
        </div>
    </div>
    <!-- End Links ban-->
    <!-- Start Banner -->
    <section class="sub-banner">
        <h1>@Model.GetPropertyValue("title")</h1>
        <a href="/@lang/about-us/who-we-are/governance/">@Umbraco.GetDictionaryValue("Go Back")</a>
    </section>
    <!-- End Banner -->
    <!-- Start Overviwe Section -->
    <section class="overview">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 left-side">
                    @Html.Raw(Model.GetPropertyValue("description"))
                </div>
                <div class="col-lg-6">
                    <img src="@image.Url" alt="@Model.GetPropertyValue("title")">
                </div>
            </div>
        </div>
    </section>
    <!-- End Overviwe Section -->
</main>

IIA/Views/BecomeQualified.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@using CMS.Helpers;
@{

    Layout = "Master.cshtml";
    var currentPage = Model.AncestorOrSelf();
    int pageId = UmbracoContext.Current.PageId.Value;
    var lang = Utility.GetLanguage(pageId);
    var childreen = Model.Children.Where(x => x.IsVisible()).ToList();
    var i = 0;
}

<!-- Start Main Content -->
<main class="main">
    <!-- Start Links ban-->
    @Html.Partial("Breadcrumb")
    <!-- End Links ban-->
    <!-- Start Banner -->
    @Html.Partial("TopBannerImage")
    <!-- End Banner -->
    <!-- Start Become Section-->
    <section class="official">
        <div class="container" data-aos="zoom-in" data-aos-offset="" data-aos-duration="2000" data-aos-delay="100" data-aos-easing="ease-in-sine" data-aos-anchor-placement="top-bottom">
            @Html.Raw(Model.GetPropertyValue("description"))
        </div>
    </section>

    <!-- Start About Section-->
    <section class="about-sec">
        @foreach (var item in childreen)
        {
            var Image = item.GetPropertyValue<IPublishedContent>("bigImage");
            if (i % 2 == 0)
            {
                <div class="left-content sec sec1" style="background-image: url(@Image.Url);">
                    <div class="fade-right-sec" data-aos="fade-right" data-aos-offset="" data-aos-duration="1000" data-aos-delay="100" data-aos-easing="ease-in-sine" data-aos-anchor-placement="top-bottom">
                        <div class="content">
                            <h3>@item.GetPropertyValue("title")</h3>
                            <p>@item.GetPropertyValue("introduction")</p>
                            <a href="@item.Url" class="btn btn-light">@Umbraco.GetDictionaryValue("Know More")</a>
                            </div>
                        </div>
                </div>
            }
            else
            {
                <div class="right-content sec sec2" style="background-image: url(@Image.Url);">
                    <div class="fade-left-sec" data-aos="fade-left" data-aos-offset="" data-aos-duration="1000" data-aos-delay="100" data-aos-easing="ease-in-sine" data-aos-anchor-placement="top-bottom">
                        <div class="content">
                            <h3>@item.GetPropertyValue("title")</h3>
                            <p>@item.GetPropertyValue("introduction")</p>
                            <a href="@item.Url" class="btn btn-light">@Umbraco.GetDictionaryValue("Know More")</a>
                        </div>
                    </div>

                </div>
            }
            i++;
        }

    </section>

    <!-- Start Membership Section -->
    <section class="membership">
        <div class="container">
            <div class="text-center">
                <h2>@Model.GetPropertyValue("membershipHeading")</h2>
                <p>@Model.GetPropertyValue("membershipSubText")</p>
            </div>
            <div class="row">
                @foreach (var item in childreen)
                {
                    var typeOfMembership = item.GetPropertyValue("typeOfMembership").ToString();
                    if (typeOfMembership == "Students" || typeOfMembership == "Individuals")
                    {
                        <div class="col-md-4 col-12" data-aos="fade-right" data-aos-offset="" data-aos-duration="1000" data-aos-delay="100" data-aos-easing="ease-in-sine" data-aos-anchor-placement="top-bottom">
                            <div class="card-membership">
                                <h3>@Umbraco.GetDictionaryValue(item.GetPropertyValue("typeOfMembership").ToString())</h3>
                                <p>@item.GetPropertyValue("membershipShortNotes")</p>
                                <ul class="list-unstyled">
                                    <li>
                                        <div class="left-side">
                                            <h5> @Umbraco.GetDictionaryValue("Discount")</h5> <span>@item.GetPropertyValue("generalDiscount")%</span>
                                        </div>
                                        <div class="right-side">
                                            <h5> @Umbraco.GetDictionaryValue("Price")</h5> <span> SAR @String.Format("{0:n2}", Convert.ToDouble(item.GetPropertyValue("generalFee").ToString()) + (double.Parse(item.GetPropertyValue("generalFee").ToString()) * 15) / 100)</span>
                                        </div>
                                    </li>
                                </ul>
                                <a href="/@lang/registration/member-register/" class="btn btn-light">@Umbraco.GetDictionaryValue("Register Now")</a>
                            </div>
                        </div>
                    }
                    else if (typeOfMembership == "Corporate")
                    {
                        <div class="col-md-4 col-12" data-aos="fade-left" data-aos-offset="" data-aos-duration="1000" data-aos-delay="100" data-aos-easing="ease-in-sine" data-aos-anchor-placement="top-bottom">
                            <div class="card-membership">
                                <h3>@Umbraco.GetDictionaryValue(item.GetPropertyValue("typeOfMembership").ToString())</h3>
                                <p>@item.GetPropertyValue("membershipShortNotes")</p>
                                <ul class="list-unstyled">
                                    <li>
                                        <h4>@Umbraco.GetDictionaryValue("Gold")</h4>
                                        <div class="left-side">
                                            <h5> @Umbraco.GetDictionaryValue("Discount")</h5> <span>@item.GetPropertyValue("goldDiscount")%</span>
                                        </div>
                                        <div class="right-side">
                                            <h5> @Umbraco.GetDictionaryValue("Price")</h5> <span> SAR @String.Format("{0:n0}", Convert.ToDouble(item.GetPropertyValue("goldFee").ToString()) + (double.Parse(item.GetPropertyValue("goldFee").ToString()) * 15) / 100)</span>
                                        </div>
                                    </li>
                                    <li>
                                        <h4>@Umbraco.GetDictionaryValue("Silver")</h4>
                                        <div class="left-side">
                                            <h5> @Umbraco.GetDictionaryValue("Discount")</h5> <span>@item.GetPropertyValue("silverDiscount")%</span>
                                        </div>
                                        <div class="right-side">
                                            <h5> @Umbraco.GetDictionaryValue("Price")</h5> <span> SAR @String.Format("{0:n0}", Convert.ToDouble(item.GetPropertyValue("silverFee").ToString()) + (double.Parse(item.GetPropertyValue("silverFee").ToString()) * 15) / 100)</span>
                                        </div>
                                    </li>
                                    <li>
                                        <h4>@Umbraco.GetDictionaryValue("Bronze")</h4>
                                        <div class="left-side">
                                            <h5> @Umbraco.GetDictionaryValue("Discount")</h5> <span>@item.GetPropertyValue("bronzeDiscount")%</span>
                                        </div>
                                        <div class="right-side">
                                            <h5> @Umbraco.GetDictionaryValue("Price")</h5> <span> SAR @String.Format("{0:n0}", Convert.ToDouble(item.GetPropertyValue("bronzeFee").ToString()) + (double.Parse(item.GetPropertyValue("bronzeFee").ToString()) * 15) / 100)</span>
                                        </div>
                                    </li>

                                </ul>
                                <a href="/@lang/registration/member-register/" class="btn btn-light">@Umbraco.GetDictionaryValue("Register Now")</a>
                            </div>
                        </div>                        
                    }
                }

            </div>
        </div>
    </section>
</main>
<!-- Start Footer-->

IIA/Views/Dashboard.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@using CMS.Helpers;
@{

    Layout = "Master.cshtml";
    var currentPage = Model.AncestorOrSelf();
    int pageId = UmbracoContext.Current.PageId.Value;
    var lang = Utility.GetLanguage(pageId);
    var TopImage = Model.GetPropertyValue<IPublishedContent>("TopImage");
}
@section Header
{
    <link href="/ui/stylesheet/developer-dashboard.css" rel="stylesheet">
    <link href="/ui/stylesheet/step-wizard.css" rel="stylesheet">
}
<!-- Start Main Content -->
<main class="main">
    <!-- Start Links ban-->
    @Html.Partial("Breadcrumb")
    <!-- End Links ban-->
    <!-- Start Banner -->
    <section class="banner-profile" style="background-image:url(@TopImage.Url)"></section>
    <!-- End Banner -->
    <!-- Start user navbar-->
    @{Html.RenderAction("TopMenu", "Dashboard");}

    <!-- Start Content -->
    <section class="content-dashboard">
        <div class="container-fluid padd-0">
            <div class="row">
                <div class="sidebar col-lg-3 col-md-2 col-12">
                    @{Html.RenderAction("LeftMenu", "Dashboard");}
                </div>
                @Html.Raw(Model.GetPropertyValue("pageSection"))
            </div>
        </div>
    </section>
</main>
<!-- Start Footer-->

IIA/Views/RegisterPaymentGatewayResponse.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@using CMS.Helpers;
@{

    int pageId = UmbracoContext.Current.PageId.Value;
    var lang = Utility.GetLanguage(pageId);
    var pageContent = Umbraco.TypedContent(pageId);
    string Id = Request.QueryString["id"];
    string resourcePath = Request.QueryString["resourcePath"];
    if (Id != null && resourcePath != null)
    {
        Utility.CheckRegistrationPaymentStatus(Id, resourcePath, lang);
    }
    else
    {
        Utility.CheckRegistrationPaymentStatus("", "", lang);
    }

}

<!-- Start Main Content -->
<main class="main">
    <!-- Start Links ban-->
    @Html.Partial("Breadcrumb")

</main>
<!-- Start Footer-->